name: Send Discord Commit Message
on: [push]
jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
    - name: Commit Notify
      uses: Sniddl/discord-commits@v1.6
      with:
        # discord webhook url without /github
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        template: "avatar-with-link"
        include-extras: false
        include-footer: false
